Repository TwoDariTeam/tourismDiary, pull requests merged in 2023-11, with the labels that each got.

#5 환경변수 변경
  src/main/java/com/team/twodari/board/entity/BoardEntity.java
  src/main/java/com/team/twodari/category/entity/CategoryEntity.java
  src/main/java/com/team/twodari/common/entity/BaseEntity.java
  src/main/java/com/team/twodari/common/entity/MutableBaseEntity.java
  src/main/java/com/team/twodari/image/entity/ImageEntity.java
  src/main/java/com/team/twodari/reply/entity/ReplyEntity.java
  src/main/java/com/team/twodari/tag/entity/TagEntity.java
  src/main/java/com/team/twodari/user/entity/UserEntity.java
Labels: documentation, enhancement

#9 etc: ComResponseEntity config
  src/main/java/com/team/twodari/common/ComResponseEntity.java
  src/main/java/com/team/twodari/common/constant/UserRoleConfig.java
  src/main/java/com/team/twodari/common/dto/ComResponseDTO.java
  src/main/java/com/team/twodari/common/entity/BaseEntity.java
  src/main/java/com/team/twodari/user/controller/UserController.java
  src/main/java/com/team/twodari/user/entity/UserEntity.java
  src/test/java/com/team/twodari/Test1.java
Labels: documentation, enhancement

#14 Board, SubBoard CUD 기능 구현
  src/main/java/com/team/twodari/board/controller/BoardController.java
  src/main/java/com/team/twodari/board/dto/BoardCreateDto.java
  src/main/java/com/team/twodari/board/dto/BoardUpdateDto.java
  src/main/java/com/team/twodari/board/entity/BoardEntity.java
  src/main/java/com/team/twodari/board/service/BoardService.java
  src/main/java/com/team/twodari/subBoard/controller/SubBoardController.java
  src/main/java/com/team/twodari/subBoard/dto/SubBoardCreateDto.java
  src/main/java/com/team/twodari/subBoard/dto/SubBoardUpdateDto.java
  src/main/java/com/team/twodari/subBoard/entity/SubBoardEntity.java
  src/main/java/com/team/twodari/subBoard/repository/SubBoardRepository.java
  src/main/java/com/team/twodari/subBoard/service/SubBoardService.java
  src/main/resources/application-environment-example.yml
Labels: enhancement

#19 [FEAT] 게시글 soft delete 변경사항, 이미지 기능 추가
  build.gradle
  src/main/java/com/team/twodari/board/controller/BoardController.java
  src/main/java/com/team/twodari/board/dto/BoardCreateDto.java
  src/main/java/com/team/twodari/board/dto/BoardReadDto.java
  src/main/java/com/team/twodari/board/dto/BoardUpdateDto.java
  src/main/java/com/team/twodari/board/entity/BoardEntity.java
  src/main/java/com/team/twodari/board/service/BoardService.java
  src/main/java/com/team/twodari/common/config/s3/S3Config.java
  src/main/java/com/team/twodari/image/controller/ImageController.java
  src/main/java/com/team/twodari/image/entity/ImageEntity.java
  src/main/java/com/team/twodari/image/repository/ImageRepository.java
  src/main/java/com/team/twodari/image/service/ImageService.java
  src/main/java/com/team/twodari/image/service/S3UploadService.java
  src/main/java/com/team/twodari/subBoard/dto/SubBoardCreateDto.java
  src/main/java/com/team/twodari/subBoard/dto/SubBoardReadDto.java
  src/main/java/com/team/twodari/subBoard/dto/SubBoardUpdateDto.java
  src/main/java/com/team/twodari/subBoard/entity/SubBoardEntity.java
  src/main/java/com/team/twodari/subBoard/service/SubBoardService.java
  src/main/resources/application.yml
  src/test/java/com/team/twodari/base/BaseControllerTest.java
  src/test/resources/application.yml
Labels: enhancement

#22 [FEAT] 게시글과 이미지 삭제 변경, board 이미지 기능 추가, board introduce 필드 추가
  src/main/java/com/team/twodari/board/controller/BoardController.java
  src/main/java/com/team/twodari/board/dto/BoardCreateDto.java
  src/main/java/com/team/twodari/board/dto/BoardReadDto.java
  src/main/java/com/team/twodari/board/dto/BoardUpdateDto.java
  src/main/java/com/team/twodari/board/entity/BoardEntity.java
  src/main/java/com/team/twodari/board/service/BoardService.java
  src/main/java/com/team/twodari/common/service/S3UploadService.java
  src/main/java/com/team/twodari/image/controller/BoardImageController.java
  src/main/java/com/team/twodari/image/controller/ImageController.java
  src/main/java/com/team/twodari/image/controller/SubBoardImageController.java
  src/main/java/com/team/twodari/image/controller/UserImageController.java
  src/main/java/com/team/twodari/image/entity/BoardImageEntity.java
  src/main/java/com/team/twodari/image/entity/SubBoardImageEntity.java
  src/main/java/com/team/twodari/image/entity/UserImageEntity.java
  src/main/java/com/team/twodari/image/repository/BoardImageRepository.java
  src/main/java/com/team/twodari/image/repository/ImageRepository.java
  src/main/java/com/team/twodari/image/repository/SubBoardImageRepository.java
  src/main/java/com/team/twodari/image/repository/UserImageRepository.java
  src/main/java/com/team/twodari/image/service/BoardImageService.java
  src/main/java/com/team/twodari/image/service/SubBoardImageService.java
  src/main/java/com/team/twodari/image/service/UserImageService.java
  src/main/java/com/team/twodari/subBoard/controller/SubBoardController.java
  src/main/java/com/team/twodari/subBoard/entity/SubBoardEntity.java
  src/main/java/com/team/twodari/subBoard/service/SubBoardService.java
  src/test/java/com/team/twodari/base/BaseControllerTest.java
Labels: enhancement

#23 [FEAT]UserController Fin
  .run/TwodariApplication.run.xml
  build.gradle
  src/main/java/com/team/twodari/TwodariApplication.java
  src/main/java/com/team/twodari/admin/user/AdminUserService.java
  src/main/java/com/team/twodari/common/config/jwt/JwtSecurityConfig.java
  src/main/java/com/team/twodari/common/config/security/AuthenticationConfig.java
  src/main/java/com/team/twodari/common/config/security/JwtSecurityConfig.java
  src/main/java/com/team/twodari/common/config/security/SpringSecurityConfig.java
  src/main/java/com/team/twodari/common/constant/Constant.java
  src/main/java/com/team/twodari/common/constant/PasswordGeneratorConstant.java
  src/main/java/com/team/twodari/common/constant/RegularExpression.java
  src/main/java/com/team/twodari/common/constant/UserRoleConfig.java
  src/main/java/com/team/twodari/common/dto/User.java
  src/main/java/com/team/twodari/common/entity/BaseEntity.java
  src/main/java/com/team/twodari/common/security/jwt/CustomUserDetailsService.java
  src/main/java/com/team/twodari/common/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/team/twodari/common/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/team/twodari/common/security/jwt/JwtFilter.java
  src/main/java/com/team/twodari/common/security/jwt/LongRoleAuthority.java
  src/main/java/com/team/twodari/common/security/jwt/TokenProvider.java
  src/main/java/com/team/twodari/global/util/PasswordGenerator.java
  src/main/java/com/team/twodari/user/controller/UserController.java
  src/main/java/com/team/twodari/user/dto/CreateUser.java
  src/main/java/com/team/twodari/user/dto/DeleteUser.java
  src/main/java/com/team/twodari/user/dto/Login.java
  src/main/java/com/team/twodari/user/dto/SearchPassword.java
  src/main/java/com/team/twodari/user/dto/UpdatePassword.java
  src/main/java/com/team/twodari/user/dto/UpdateUserInfo.java
  src/main/java/com/team/twodari/user/entity/LoginEntity.java
  src/main/java/com/team/twodari/user/entity/LoginEntityImpl.java
  src/main/java/com/team/twodari/user/entity/RoleEntity.java
  src/main/java/com/team/twodari/user/entity/UserEntity.java
  src/main/java/com/team/twodari/user/repository/UserRepository.java
  src/main/java/com/team/twodari/user/repository/UserRoleRepository.java
  src/main/java/com/team/twodari/user/service/UserService.java
  src/main/resources/application-db.yml
  src/test/java/com/team/twodari/TwodariApplicationTests.java
  src/test/java/com/team/twodari/base/BaseControllerTest.java
  src/test/java/com/team/twodari/base/FilterChainConfig.java
  src/test/java/com/team/twodari/board/controller/BoardMyPageControllerTest.java
  src/test/java/com/team/twodari/random.java
  src/test/java/com/team/twodari/user/entity/UserEntityTest.java
Labels: documentation, enhancement

#24 [Feat]: 컨트롤러 별로 dto를 생성 및 사용, QueryProjection -> Projection으로 변경
  src/main/java/com/team/twodari/board/dto/BoardEntityDto.java
  src/main/java/com/team/twodari/board/repository/BoardSearchRepository.java
  src/main/java/com/team/twodari/board/repository/BoardSearchRepositoryImpl.java
  src/main/java/com/team/twodari/board/service/BoardSearchService.java
  src/main/java/com/team/twodari/platform/controller/PlatformController.java
  src/main/java/com/team/twodari/platform/dto/BoardContainsStringDto.java
  src/main/java/com/team/twodari/platform/dto/BoardDateDto.java
  src/main/java/com/team/twodari/platform/dto/BoardPointDto.java
  src/main/java/com/team/twodari/platform/service/PlatformService.java
  src/main/java/com/team/twodari/point/repository/PointRepository.java
  src/test/java/com/team/twodari/board/repository/BoardSearchRepositoryImplTest.java
  src/test/java/com/team/twodari/board/service/BoardSearchServiceTest.java
Labels: enhancement

#28 Feat : Spring Security
  build.gradle
  src/main/java/com/team/twodari/common/config/security/CorsConfig.java
  src/main/java/com/team/twodari/common/config/security/JwtSecurityConfig.java
  src/main/java/com/team/twodari/common/config/security/SpringSecurityConfig.java
  src/main/java/com/team/twodari/common/config/security/WebSecurityConfig_teacher.java
  src/main/java/com/team/twodari/common/constant/Constant.java
  src/main/java/com/team/twodari/common/security/jwt/TokenProvider.java
  src/main/java/com/team/twodari/user/controller/UserController.java
  src/main/java/com/team/twodari/user/entity/LoginEntityImpl.java
  src/main/java/com/team/twodari/user/entity/UserEntity.java
  src/main/java/com/team/twodari/user/repository/UserRepository.java
  src/main/java/com/team/twodari/user/repository/UserRoleRepository.java
  src/main/java/com/team/twodari/user/service/UserService.java
  src/main/resources/application-db.yml
Labels: documentation, enhancement

#30 [Fix] Spring Security
  build.gradle
  src/main/java/com/team/twodari/common/security/jwt/JwtFilter.java
  src/main/java/com/team/twodari/common/security/jwt/TokenProvider.java
Labels: documentation
